services:
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    restart: always
    environment:
      - node.name=opensearch
      - "DISABLE_SECURITY_PLUGIN=true"
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - opensearch:/usr/share/opensearch/data
    ports:
      - "9200:9200"

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    restart: always
    ports:
      - "3000:3000"


volumes:
  n8n:
  opensearch:
